Added serverless
saic-oss/anvil pull request #26
Opened 2021-08-11 19:48 UTC by shawju

## what
* Added [serverless](https://github.com/serverless/serverless)

## why
* Need to use serverless to create Lambdas

## references

2021-08-11 19:56 UTC, shawju commented
/test

2021-08-11 20:17 UTC, bstascavage submitted a review, later dismissed

2021-08-11 20:18 UTC, bstascavage commented
@shawju make sure you have your settings correct: https://github.com/saic-oss/anvil/pull/23#issuecomment-845970024

2021-08-11 20:42 UTC, shawju commented
/test

2021-08-12 16:50 UTC, shawju commented
/test

2021-08-12 17:30 UTC, shawju commented
/test

2021-08-12 18:29 UTC, shawju commented
/test

2021-08-12 20:13 UTC, shawju commented
/test

2021-08-12 20:54 UTC, shawju commented
/test

2021-08-13 13:41 UTC, shawju commented
/test

2021-08-13 14:20 UTC, shawju commented
/test

2021-08-13 14:48 UTC, shawju commented
/test

2021-08-13 15:13 UTC, shawju commented
/test

2021-08-13 15:25 UTC, shawju commented
/test

2021-08-13 15:56 UTC, shawju commented
/test

2021-08-13 17:12 UTC, shawju commented
/test

2021-08-13 17:19 UTC, bstascavage commented
/test

2021-08-13 17:49 UTC, RothAndrew commented
/test

2021-08-14 04:41 UTC, RothAndrew commented
/test

2021-08-16 15:36 UTC, shawju commented
/test

2021-08-16 15:42 UTC, shawju commented
/test

2021-08-16 16:59 UTC, RothAndrew requested changes
- Delete src/.DS_Store

Other than that it LGTM

2021-08-16 17:03 UTC, RothAndrew commented
I'm reviewing from a compliance perspective only. Should get another approval from anvil team before merging

2021-08-16 17:34 UTC, bstascavage requested changes
We shouldn't be adding `hadolint` ignores unless we explicitly need the acception.

2021-08-16 17:34 UTC, bstascavage commented on src/docker/Dockerfile
> +# hadolint ignore=DL3003,DL3047
I don't think we want this ignore here.  We should update `wget` to use the `--progress` flag.

See [here](https://github-wiki-see.page/m/hadolint/hadolint/wiki/DL3047)

2021-08-16 17:34 UTC, bstascavage commented on src/docker/Dockerfile
> +# hadolint ignore=DL3042
I don't think we want this ignore here.

See [here](https://github-wiki-see.page/m/hadolint/hadolint/wiki/DL3042)

2021-08-16 17:34 UTC, bstascavage commented on src/docker/Dockerfile
> +# hadolint ignore=DL3059
What does this do?

2021-08-16 18:25 UTC, shawju commented
/test

2021-08-16 18:32 UTC, bstascavage approved these changes
LGTM

2021-08-16 18:33 UTC, bstascavage requested changes

2021-08-16 18:33 UTC, bstascavage commented on spec/skopeo_spec.sh
> +It "validates tool is installed by checking version"
One last thing

This file needs to be indented like the other `shellspec` files

2021-08-16 18:37 UTC, shawju commented
/test

2021-08-16 19:58 UTC, shawju commented
/test

2021-08-16 19:58 UTC, RothAndrew approved these changes
Approving from compliance perspective only. Get a 2nd from @saic-oss/anvil

2021-08-16 23:46 UTC, bstascavage approved these changes
LGTM

2021-08-17 16:22 UTC, merged